---
name: ExtUtils-CBuilder
version: 0.27
author:
  - 'Ken Williams, kwilliams@cpan.org'
abstract: Compile and link C code for Perl modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.perl.org/modules/ExtUtils-CBuilder
build_requires:
  Test::More: 0.47
requires:
  Cwd: 0
  File::Basename: 0
  File::Spec: 0
  IO::File: 0
  Text::ParseWords: 0
provides:
  ExtUtils::CBuilder:
    file: lib/ExtUtils/CBuilder.pm
    version: 0.27
  ExtUtils::CBuilder::Base:
    file: lib/ExtUtils/CBuilder/Base.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::Unix:
    file: lib/ExtUtils/CBuilder/Platform/Unix.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::VMS:
    file: lib/ExtUtils/CBuilder/Platform/VMS.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::Windows:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::Windows::BCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/BCC.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::Windows::GCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::Windows::MSVC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/MSVC.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::aix:
    file: lib/ExtUtils/CBuilder/Platform/aix.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::cygwin:
    file: lib/ExtUtils/CBuilder/Platform/cygwin.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::darwin:
    file: lib/ExtUtils/CBuilder/Platform/darwin.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::dec_osf:
    file: lib/ExtUtils/CBuilder/Platform/dec_osf.pm
    version: 0.27
  ExtUtils::CBuilder::Platform::os2:
    file: lib/ExtUtils/CBuilder/Platform/os2.pm
    version: 0.27
generated_by: Module::Build version 0.3502
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
