---
abstract: 'Compile and link C code for Perl modules'
author:
  - 'Ken Williams, kwilliams@cpan.org'
build_requires:
  Test::More: 0.47
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-CBuilder
provides:
  ExtUtils::CBuilder:
    file: lib/ExtUtils/CBuilder.pm
    version: 0.2703
  ExtUtils::CBuilder::Base:
    file: lib/ExtUtils/CBuilder/Base.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::Unix:
    file: lib/ExtUtils/CBuilder/Platform/Unix.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::VMS:
    file: lib/ExtUtils/CBuilder/Platform/VMS.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::Windows:
    file: lib/ExtUtils/CBuilder/Platform/Windows.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::Windows::BCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/BCC.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::Windows::GCC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::Windows::MSVC:
    file: lib/ExtUtils/CBuilder/Platform/Windows/MSVC.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::aix:
    file: lib/ExtUtils/CBuilder/Platform/aix.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::cygwin:
    file: lib/ExtUtils/CBuilder/Platform/cygwin.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::darwin:
    file: lib/ExtUtils/CBuilder/Platform/darwin.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::dec_osf:
    file: lib/ExtUtils/CBuilder/Platform/dec_osf.pm
    version: 0.2703
  ExtUtils::CBuilder::Platform::os2:
    file: lib/ExtUtils/CBuilder/Platform/os2.pm
    version: 0.2703
requires:
  Cwd: 0
  File::Basename: 0
  File::Spec: 0
  IO::File: 0
  Text::ParseWords: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dagolden/extutils-cbuilder.git
version: 0.2703
